---PROJECT 3: SQL DATA ANALYSIS---

--- USING SELECT ---
--Query 1: Display all records
SELECT * FROM ecommerce;

--Query 2: Display selected columns
-- This query retrieves only the orderid, product, quantity & totalprice columns
SELECT orderid,product,quantity,totalprice
FROM ecommerce;

--- USING WHERE ---
--Query 3: Find all delivered orders
-- This query filters the dataset to display only orders whose status is Delivered
SELECT * FROM ecommerce
WHERE orderstatus = 'Delivered';

--Query 4: Find all laptops orders
-- This query returns only the orders where product purchased is a Laptop
SELECT * FROM ecommerce
WHERE product ='Laptop';

--Query 5: Orders paid with credit card
-- This query displays all transactions completed using credit card as means of payment
SELECT * FROM ecommerce
WHERE paymentmethod = 'Credit Card';

--- USING ORDER BY ---
--Query 6: Sort orders by total price
-- This query sorts all orders from the highest total price to the lowest
SELECT * FROM ecommerce
ORDER BY totalprice DESC;

--Query 7: Sort orders by quantity
-- This query sorts the orders based on the quantity purchased starting with the smallest quantity
SELECT * FROM ecommerce
ORDER BY quantity ASC;

--- USING COUNT ---
--Query 8: Total number of orders recorded
-- This query counts the total number of orders recorded
SELECT COUNT(*) AS totalorders
FROM ecommerce;

--Query 9: Total numbers of orders by status
-- This query groups the orders by orderstatus & counts how many belong to each status
SELECT orderstatus,
COUNT(*) AS numberoforders
FROM ecommerce
GROUP BY orderstatus;

ALTER TABLE ecommerce
ALTER COLUMN totalprice TYPE NUMERIC
USING REPLACE(REPLACE(totalprice,'$',''),',','')::NUMERIC;

--Query 10: Total sales recorded
-- This query calculates the overall sales revenue by adding all values in the totalprice column
SELECT SUM(totalprice) AS totalsales
FROM ecommerce;

--Query 11: Total sales recorded by paymentmethod
-- This query calculates the total sales generated by each payment method
SELECT paymentmethod,SUM(totalprice) AS totalsales
FROM ecommerce
GROUP BY paymentmethod
ORDER BY totalsales DESC;

--Query 12: Total sales recorded by referralsource
-- This query shows how much revenue each referralsource generated
SELECT referralsource,SUM(totalprice) AS totalsales
FROM ecommerce
GROUP BY referralsource
ORDER BY totalsales DESC;

--Query 13: Total average order value
-- This query calculates the average amount spent per order
SELECT AVG(totalprice) AS averageordervalue
FROM ecommerce;

--Query 14: Average order value by product
-- This query calculates the average order value for each product
SELECT product,AVG(totalprice) AS averageordervalue
FROM ecommerce
GROUP BY product
ORDER BY averageordervalue DESC;

--Query 15: Total numbers of customer by referralsource
-- This query counts the number of orders associated with referralsource
SELECT referralsource, COUNT(*) AS totalcustomers
FROM ecommerce
GROUP BY referralsource;

--Query 16: Average quantity purchased by product
-- This query calculates the average quatity ordered for each product
SELECT product, AVG(quantity) AS averagequantity
FROM ecommerce
GROUP BY product;
